【臺北大學】Python程式設計<br>
【授課老師】[陳祥輝 (Email : HsiangHui.Chen@gmail.com)](mailto:HsiangHui.Chen@gmail.com)<br>
【facebook】[陳祥輝老師的臉書 (歡迎加好友)](https://goo.gl/osivhx)<br>
【參考書籍】[從零開始學Python程式設計（適用Python 3.5以上）](http://www.drmaster.com.tw/Bookinfo.asp?BookID=MP31821)<br>
【主要議題】流程控制與迴圈

【重點提要】
1. 循序結構(Sequential)
2. 選擇結構(Selection) : 
    * if ... elif ... elif ... else 
    * X if C else Y
3. 迭代結構(Iteration) : for / while, break / continue

【參考資料】
* [有關在 matplotlib 顯示數學表示式 (LaTex)](https://wizardforcel.gitbooks.io/matplotlib-user-guide/4.6.html)

【比較以下不同用法的差異】
* import numpy as np
* import numpy.random as rnd1
* from numpy import random as rnd2
* from numpy.random import random

In [1]:
#-*-coding:UTF-8-*- 
from platform import python_version
import os, time, glob, socket

print("【日期時間】{}".format(time.strftime("%Y/%m/%d %H:%M:%S")))
print("【工作目錄】{}".format(os.getcwd()))
print("【主機名稱】{} ({})".format(socket.gethostname(),socket.gethostbyname(socket.gethostname())))
print("【Python】{}".format(python_version()))

%autosave 120

【日期時間】2021/03/16 13:31:32
【工作目錄】C:\Users\NTPU Computer Center\Desktop
【主機名稱】1MF08-06 (10.137.110.6)
【Python】3.8.5


Autosaving every 120 seconds


## <font color=#0000FF>Python的基本資料型態</font>

### Python Primitive data types (基本資料型態)

* Numeric Types 
    - int()：整數
    - float()：小數
    - complex()：複數
    
* bool()：布林值<br>
比較特殊的是True是0以外的其他數字，False是0<br>
若將布林值轉成數字True為1，False為0

* str()：字串
* None：空值

要查詢各個資料型態可以使用type()

In [2]:
print(type(10))
print(type(10.0))

<class 'int'>
<class 'float'>


In [3]:
int('10') + 5     # 將字串 '10' 轉換成整數的 10

15

In [4]:
complex(3)

(3+0j)

In [5]:
print(type(True))
print(type(False))

<class 'bool'>
<class 'bool'>


In [6]:
print(bool(0))     #False
print(bool(10))    #非 0 皆轉換出 True
print(bool(-10))

False
True
True


In [7]:
print(int(True))    # 1
print(int(False))   # 0

1
0


In [8]:
sum([True, True, False])

2

In [9]:
str(10)

'10'

In [10]:
print(str(10))     #因為 print() 是將結果輸出畫面，所以不會有引號

10


In [11]:
print('python')

python


## <font color=#0000FF>import模組的各種寫法</font>

【比較以下不同用法的差異】
* import numpy as np
* from numpy import *
* import numpy.random as rnd1
* from numpy import random as rnd2
* from numpy.random import *
* from numpy.random import random

<table>
<tr><td>
<img src='http://180.218.162.136:2018/images/Python/importDiag.png' width=400 height=300 alt="這裡是放一張 importDiag.png 的示意圖"></td><td>
<img src='http://180.218.162.136:2018/images/Python//importNumpy.png' width=400 height=300 alt="這裡是放一張 importNumpy.png 的示意圖">
</td></tr>
</table>

<font size=4>【方法一】</font>

In [12]:
import numpy as np

In [13]:
#查看np安裝的目錄
np

<module 'numpy' from 'C:\\Anaconda3\\envs\\Py38\\lib\\site-packages\\numpy\\__init__.py'>

In [14]:
#np.底下的子套件（子目錄）裡面的random函數
print(np.random.random())

0.525576254287092


<font size=4>【方法二】</font>

In [20]:
#兩種方法都可以匯入
import numpy.random as rnd1
from numpy import random as rnd2

In [21]:
print(rnd1.random())
print(rnd2.random())

0.412574394150795
0.1416920629467603


np.random.seed()：設定固定數值，但僅限於同一次執行（同一個block）有效

In [24]:
np.random.seed(322)
print(rnd1.random())
print(rnd2.random())

0.412574394150795
0.1416920629467603


<font size=4>【方法三】盡量不要使用，怕會覆蓋掉原始函數，若要使用，要特別注意</font>

In [27]:
from numpy.random import random     #匯入在numpy.random下的random函數
#下面千萬不要使用
#from numpy.random import *

In [28]:
print(random())

0.017414696212477043


## <font color=#0000FF>選擇結構(Selection)</font>

<font color=#0000FF>
if ... elif ... elif ... else ...
</font>

In [29]:
usr = input("請輸入一個數值：")    #input內輸入的皆為string
if usr == 10 :
    print("答對了")
else :
    print("答錯了")

請輸入一個數值：10
答錯了


In [30]:
usr = input("請輸入一個數值：")
print(type(usr))

usr = int(usr)    #將usr轉成數值

if usr == 10 :
    print("答對了")
else :
    print("答錯了")

請輸入一個數值：10
<class 'str'>
答對了


In [31]:
usr = int(input("請輸入一個數值："))
print(type(usr))

if usr == 10 :
    print("答對了")
else :
    print("答錯了")

請輸入一個數值：10
<class 'int'>
答對了


In [35]:
usr = input("請輸入一個數值：")
str.isdigit
if usr.isdigit():
    if int(usr) == 10:
        print("答對了")
    else :
        print("答錯了")
else:
    print("輸入錯誤，請輸入數值")
    #input("請再輸入一個數值：")，如果要做到真的有輸入數值，那可能要加上while

請輸入一個數值：22235
答錯了


<font size=4>常用的隨機亂數</font>

In [36]:
print(np.random.random())
print(np.random.randn(3, 2))
print(np.random.randn(3, 2, 4))

0.5779465059479731
[[-0.16593173 -0.12713842]
 [-0.531414   -0.63057186]
 [ 0.55854137  0.80939166]]
[[[ 1.16245909  0.76125496 -0.15352669 -0.09104025]
  [-0.59861623  1.20393989  0.40108692  0.0474649 ]]

 [[-1.3550557   0.0371816   0.67128033  0.17890541]
  [-0.29145873  1.01555816 -0.58149538 -0.15592595]]

 [[ 0.0080926  -1.59772516  0.25400758 -0.42348847]
  [ 0.8699099  -0.41801223 -0.2496089  -1.19507074]]]


In [37]:
print(np.random.randint(11, 21))
print(np.random.randint(11, 21, 3))   # [ ]  : list object

19
[14 14 15]


In [38]:
print(np.random.choice([1,2,3,4,5,6],  5, replace=False))   # R : sample()
print(np.random.choice([1,2,3,4,5,6], 10, replace=True))

[1 5 3 2 4]
[1 5 2 6 5 6 4 1 6 5]


<font size=3>【練習】：電腦產生一個1-100的亂數，使用者猜猜看</font>
- 答對
- 距離5之內的 : 接近
- 距離大於 5 : 太大
- 距離大於-5 : 太小

In [43]:
#比較不好的程式
myans = np.random.randint(1,101)
print(myans)

usr = int(input("請輸入一個數值："))

if usr == myans :
    print("答對了")
elif abs(usr-myans)<=5 :
    print("很接近咯")
elif usr-myans>5 :
    print("太大了")
else :
    print("太小了")

79
請輸入一個數值：79
很接近咯


盡量將能改變的數值都設定成變數，方便重複使用

In [47]:
#修改後
max_ = 100; min_ = 1

myans = np.random.randint(min_, max_+1)
print(myans)

usr = int(input("請輸入一個{} ~ {}數值：".format(min_, max_)))

if usr == myans :
    print("答對了")
elif abs(usr-myans) <= 5 :
    print("很接近咯")
elif usr-myans > 5 :
    print("太大了")
else :
    print("太小了")

54
請輸入一個1 ~ 100數值：100
太大了


<font color=#0000FF>
X if Condition（條件） else Y
</font>

In [48]:
score = np.random.randint(1, 101)
print(score)

print('及格' if score >= 60 else '不及格')

33
不及格


In [54]:
score = np.random.randint(1, 101)

print('你的成績是：{}，這次考試{}喔'.format(score, ('及格' if score >= 60 else '不及格')))

你的成績是：23，這次考試不及格喔


In [50]:
# 嚴重的錯誤示範，他跑了兩次的randint
print('你的成績是：{}，這次考試{}喔'.format(np.random.randint(1, 101), '及格' if np.random.randint(1, 101) >= 60 else '不及格'))

score = 25 : 不及格


## <font color=#0000FF>比較 range(), np.linspace(), np.arange()</font>

In [15]:
import numpy as np

<font color=#0000FF>range() : <font color=#FF0000>只可用於整數</font>，start、stop、step，含起值、不含迄值</font>

In [16]:
# range(stop) -> range object
# range(start, stop[, step]) -> range object
# Return an object that produces a sequence of integers from start (inclusive) to stop (exclusive) by step.

In [55]:
print(range(10))
print(list(range(10)))
print(list(range(11, 21)))
print(list(range(11, 21, 2)))

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[11, 13, 15, 17, 19]


<font color=#0000FF>np.arange() : 可用於整數、浮點型態，start、stop、step，含起值、不含迄值</font>

In [17]:
# np.arange([start,] stop[, step,], dtype=None) 
# Return evenly spaced values within a given interval.
#
# [note]
# stop : number
#     End of interval.  The interval does not include this value.

In [ ]:
print(np.arange(10))
print(np.arange(11, 21))
print(np.arange(11, 21, 2.5))

<font color=#0000FF>np.linspace : 可用於整數、浮點型態，start、stop、<b><u>num</u></b>，，含起值、預設有含迄值(endpoint=True)</font>

In [18]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
# Return evenly spaced numbers over a specified interval.
# 
# [note]
# stop : scalar
#     The end value of the sequence, unless `endpoint` is set to False.

# np.linspace(start=1,stop=11,num=10)
# np.linspace(start=1,stop=11,num=10,dtype=int)
# np.linspace(start=1,stop=11,num=10,retstep=True,dtype=int)
# np.linspace(start=1,stop=11,num=10,endpoint=False,retstep=True)

In [ ]:
print(np.linspace(start=11, stop=30, num=20, endpoint=True)) #endpoint
print(np.linspace(start=11, stop=30, num=20, endpoint=False))
print(np.linspace(start=11, stop=30, num=20, endpoint=False, retstep=True))

## <font color=#0000FF>迭代結構(Iteration)</font>

## <font color=#0000FF>for range 的使用(一)</font>
* range()
* np.linespace()  
* np.arange()

In [57]:
for _ in range(10) :      # _ : 代表匿名變數
    print("*")

*
*
*
*
*
*
*
*
*
*


In [58]:
for i in range(10) :
    print("i = {}".format(i))

i = 0
i = 1
i = 2
i = 3
i = 4
i = 5
i = 6
i = 7
i = 8
i = 9


In [56]:
for x in range(1, 11):
    print("x={}".format(x), end = "\r")
    time.sleep(0.5)

<font size=3>【練習】：99乘法表

In [60]:
for i in range(1, 11):
    for j in range(1,8):
        print("{} * {} = {}".format(i, j, i*j))
    print()

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14

3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21

4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28

5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35

6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42

7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49

8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56

9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63

10 * 1 = 10
10 * 2 = 20
10 * 3 = 30
10 * 4 = 40
10 * 5 = 50
10 * 6 = 60
10 * 7 = 70



<font size=3>【作業】：電腦產生一個1-100的亂數，使用者猜猜看，利用for迴圈，猜10次，印出猜到的是第幾次</font>
- 答對
- 距離5之內的 : 接近
- 距離大於 5 : 太大
- 距離大於-5 : 太小

In [ ]:
#修改後
max_ = 100; min_ = 1

myans = np.random.randint(min_, max_+1)
print(myans)

for i in range(1,11):
    usr = int(input("請輸入一個{} ~ {}數值：".format(min_, max_)))
    if usr == myans :
        yesyes = yesyes + 1 
        print("猜第{}次，答對了，這是第{}次答對".format(i, yesyes))
    elif abs(usr-myans) <= 5 :
        print("很接近咯")
    elif usr-myans > 5 :
        print("太大了")
    else :
        print("太小了")
print("在這10次中，一共猜對{}次".format(yesyes))

<font size=3>請將以下兩個 list 依據 element-wise 相加</font>

- A = [1, 2, 3]
- B = [4, 5, 6]

In [2]:
A = [1, 2, 3]
B = [4, 5, 6]
A + B

[1, 2, 3, 4, 5, 6]

In [3]:
A = [1, 2, 3]
B = [4, 5, 6]

for i in range(3):
    print(A[i] + B[i])

5
7
9


<font size=3>請將以下兩個 list 依據 element-wise 相加</font>

- A = [1, 2, 3]
- B = [4, 5, 6, 7, 8]


In [6]:
A = [1, 2, 3]
B = [4, 5, 6, 7, 8]

n = max(len(A), len(B))
print('n = {}'.format(n))

for i in range(n):
    print(A[i] + B[i])

5
7
9


IndexError: list index out of range

In [7]:
A = [1, 2, 3]
B = [4, 5, 6, 7, 8]

n = max(len(A), len(B))
print("n = {}".format(n))

for i in range(n):
    print(A[i] if i < len(A) else 0 + \
         B[i] if i < len(B) else 0)

n = 5
1
2
3
7
8


讓他變成函式

In [ ]:
def addlist(A,B):
    n = max(len(A), len(B))
    print("n = {}".format(n))

    for i in range(n):
        print(A[i] if i < len(A) else 0 + \
             B[i] if i < len(B) else 0)

不用print 用return

In [14]:
def addlist(A,B):
    n = max(len(A), len(B))
    result = [] # 1. 宣告 result 存在, 2. 給初始值
    
    for i in range(n):
        result = result + [(A[i] if i < len(A) else 0) + \
                           (B[i] if i < len(B) else 0)]
    return result

In [15]:
X = [1, 2, 3]
Y = [4, 5, 6, 7, 8, 9]
addlist(X, Y)

[5, 7, 9, 7, 8, 9]

<font size=3>【練習】：3個list相加

In [14]:
def addlist(A,B,C):
    n = max(len(A), len(B), len(C))
    result = [] # 1. 宣告 result 存在, 2. 給初始值
    
    for i in range(n):
        result = result + [(A[i] if i < len(A) else 0) + \
                           (B[i] if i < len(B) else 0) + \
                           (C[i] if i < len(C) else 0)]
    return result

## <font color=#0000FF>foreach 的使用(二)</font>

In [ ]:
os.listdir()

In [ ]:
os.listdir('c:\\')

In [ ]:
lsts = os.listdir()
n = len(lsts)
for i in range(n) :
    print(lsts[i])

In [ ]:
lsts = os.listdir()
for lst in lsts :
    print(lst)

## <font color=#0000FF>for與 dict 的使用(三)</font>

In [16]:
d1 = {"a":100, "b":200, "a":300, "c":400}       #{}：1.dict key:value, 2.set
d2 = {3:[5,6,7], 5:100, 'a':500}

<font size=3>抓取dict的value </font>
- get method會自動回傳None（這個None可以改）
- python 語法會出錯

In [17]:
print(d1.get("a"))     # 物件導向的寫法
print(d1["a"])         # Python的寫法

300
300


In [19]:
print(d1.get("X"))
print(d1["X"])

None


KeyError: 'X'

In [18]:
d2.get(3)

[5, 6, 7]

In [22]:
d1.items()

dict_items([('a', 300), ('b', 200), ('c', 400)])

In [20]:
for k, v in d1.items():
    print("key:{}, value:{}".format(k, v))

key:a, value:300
key:b, value:200
key:c, value:400


In [21]:
for (k, v) in d1.items():
    print("key:{}, value:{}".format(k, v))

key:a, value:300
key:b, value:200
key:c, value:400


## <font color=#0000FF>string module</font>

In [23]:
import string
print(string.ascii_letters)
print(string.ascii_lowercase)
print(string.ascii_uppercase)
print(string.digits)
print(string.printable)
print(string.punctuation)

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
0123456789
0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ 	

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


## <font color=#0000FF>for與 string 使用(四)</font>

In [24]:
for w in string.ascii_lowercase:
    print(w, end=" ")

a b c d e f g h i j k l m n o p q r s t u v w x y z 

In [25]:
print(list(string.ascii_lowercase))

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [26]:
lst = list("這是Python")
print(lst)

['這', '是', 'P', 'y', 't', 'h', 'o', 'n']


In [27]:
"|".join(lst)

'這|是|P|y|t|h|o|n'

## <font color=#0000FF>for與 list 使用(五)</font>
- [有關在 matplotlib 顯示數學表示式 (LaTex)](https://wizardforcel.gitbooks.io/matplotlib-user-guide/4.6.html)

<font color=#0000FF>寫一個以下數列的和</font>
- $\sum_{x=1}^{20}x^2$
- $\sum_{x=1}^{20}\sqrt{x}$
- $\sum_{x=1}^{20}\frac{1}{x}$

In [30]:
sum_ = 0
for i in range(1, 21):
    sum_ = sum_ + i**2
print(sum_)

2870


In [37]:
[x for x in range(1,21)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [29]:
sum([x**2 for x in range(1, 21)])

2870

In [33]:
sum([x**(1/2) for x in range(1, 21)])

61.66597781141981

In [35]:
sum([(1/x) for x in range(1, 21)])

3.597739657143682

<font size=3>【練習題】請將以下的文章整理，去除空白，換行符號(\n)</font>

【方法一】用replace替換，很不好的寫法

In [54]:
news = """
苗栗警分局15日傍晚接獲通報，苗栗市貓貍山公園有民眾需要協助，南苗派出所員警趕往現場，發現21名乘客手足無措，因為原本載送他們的遊覽車已自行離去，領隊臨時調不到其他車輛前往，眼看天色漸暗，不知如何是好。

警方調查，這群來自台北的乘客相約出遊，最後一站走訪苗栗市功維敘隧道，疑似乘客希望領隊請遊覽車司機把車開下山接駁，但司機認為，山下無法停車，要乘客走回山上坐車，雙方僵持不下，最後遊覽車司機竟掛電話直接把車開走。

遭丟包的乘客在貓貍山公園枯等1個多小時後，向警方求助，找來5部計程車載往後龍高鐵站，再轉搭高鐵返回台北。當時氣憤的乘客曾向員警詢問，東西都還在遊覽車上，擔心物品遭竊，還要多花近新台幣500元車資，是否可提供報案紀錄，警方則回應，相關案情都有工作紀錄，可作為日後求償依據。

苗栗縣政府消保官王德基表示，針對這起事件，遊覽車司機「不管怎麼樣都不可以把遊客丟包」，如果消費者因此產生額外的交通費用及損失，可向消保官申訴、求償。
"""

In [55]:
news = news.replace("，", "")
news = news.replace("\n", "") 
news = news.replace("。", "") 
news

'苗栗警分局15日傍晚接獲通報苗栗市貓貍山公園有民眾需要協助南苗派出所員警趕往現場發現21名乘客手足無措因為原本載送他們的遊覽車已自行離去領隊臨時調不到其他車輛前往眼看天色漸暗不知如何是好警方調查這群來自台北的乘客相約出遊最後一站走訪苗栗市功維敘隧道疑似乘客希望領隊請遊覽車司機把車開下山接駁但司機認為山下無法停車要乘客走回山上坐車雙方僵持不下最後遊覽車司機竟掛電話直接把車開走遭丟包的乘客在貓貍山公園枯等1個多小時後向警方求助找來5部計程車載往後龍高鐵站再轉搭高鐵返回台北當時氣憤的乘客曾向員警詢問東西都還在遊覽車上擔心物品遭竊還要多花近新台幣500元車資是否可提供報案紀錄警方則回應相關案情都有工作紀錄可作為日後求償依據苗栗縣政府消保官王德基表示針對這起事件遊覽車司機「不管怎麼樣都不可以把遊客丟包」如果消費者因此產生額外的交通費用及損失可向消保官申訴、求償'

【方法二】精簡的.replace

In [56]:
news = """
苗栗警分局15日傍晚接獲通報，苗栗市貓貍山公園有民眾需要協助，南苗派出所員警趕往現場，發現21名乘客手足無措，因為原本載送他們的遊覽車已自行離去，領隊臨時調不到其他車輛前往，眼看天色漸暗，不知如何是好。

警方調查，這群來自台北的乘客相約出遊，最後一站走訪苗栗市功維敘隧道，疑似乘客希望領隊請遊覽車司機把車開下山接駁，但司機認為，山下無法停車，要乘客走回山上坐車，雙方僵持不下，最後遊覽車司機竟掛電話直接把車開走。

遭丟包的乘客在貓貍山公園枯等1個多小時後，向警方求助，找來5部計程車載往後龍高鐵站，再轉搭高鐵返回台北。當時氣憤的乘客曾向員警詢問，東西都還在遊覽車上，擔心物品遭竊，還要多花近新台幣500元車資，是否可提供報案紀錄，警方則回應，相關案情都有工作紀錄，可作為日後求償依據。

苗栗縣政府消保官王德基表示，針對這起事件，遊覽車司機「不管怎麼樣都不可以把遊客丟包」，如果消費者因此產生額外的交通費用及損失，可向消保官申訴、求償。
"""

In [57]:
news.replace('\n', '').replace('，', '').replace('。','')

'苗栗警分局15日傍晚接獲通報苗栗市貓貍山公園有民眾需要協助南苗派出所員警趕往現場發現21名乘客手足無措因為原本載送他們的遊覽車已自行離去領隊臨時調不到其他車輛前往眼看天色漸暗不知如何是好警方調查這群來自台北的乘客相約出遊最後一站走訪苗栗市功維敘隧道疑似乘客希望領隊請遊覽車司機把車開下山接駁但司機認為山下無法停車要乘客走回山上坐車雙方僵持不下最後遊覽車司機竟掛電話直接把車開走遭丟包的乘客在貓貍山公園枯等1個多小時後向警方求助找來5部計程車載往後龍高鐵站再轉搭高鐵返回台北當時氣憤的乘客曾向員警詢問東西都還在遊覽車上擔心物品遭竊還要多花近新台幣500元車資是否可提供報案紀錄警方則回應相關案情都有工作紀錄可作為日後求償依據苗栗縣政府消保官王德基表示針對這起事件遊覽車司機「不管怎麼樣都不可以把遊客丟包」如果消費者因此產生額外的交通費用及損失可向消保官申訴、求償'

In [57]:
news.replace('\n', '')\
    .replace('，', '')\
    .replace('。','')

'苗栗警分局15日傍晚接獲通報苗栗市貓貍山公園有民眾需要協助南苗派出所員警趕往現場發現21名乘客手足無措因為原本載送他們的遊覽車已自行離去領隊臨時調不到其他車輛前往眼看天色漸暗不知如何是好警方調查這群來自台北的乘客相約出遊最後一站走訪苗栗市功維敘隧道疑似乘客希望領隊請遊覽車司機把車開下山接駁但司機認為山下無法停車要乘客走回山上坐車雙方僵持不下最後遊覽車司機竟掛電話直接把車開走遭丟包的乘客在貓貍山公園枯等1個多小時後向警方求助找來5部計程車載往後龍高鐵站再轉搭高鐵返回台北當時氣憤的乘客曾向員警詢問東西都還在遊覽車上擔心物品遭竊還要多花近新台幣500元車資是否可提供報案紀錄警方則回應相關案情都有工作紀錄可作為日後求償依據苗栗縣政府消保官王德基表示針對這起事件遊覽車司機「不管怎麼樣都不可以把遊客丟包」如果消費者因此產生額外的交通費用及損失可向消保官申訴、求償'

【方法三】利用list和join

In [58]:
news = """
苗栗警分局15日傍晚接獲通報，苗栗市貓貍山公園有民眾需要協助，南苗派出所員警趕往現場，發現21名乘客手足無措，因為原本載送他們的遊覽車已自行離去，領隊臨時調不到其他車輛前往，眼看天色漸暗，不知如何是好。

警方調查，這群來自台北的乘客相約出遊，最後一站走訪苗栗市功維敘隧道，疑似乘客希望領隊請遊覽車司機把車開下山接駁，但司機認為，山下無法停車，要乘客走回山上坐車，雙方僵持不下，最後遊覽車司機竟掛電話直接把車開走。

遭丟包的乘客在貓貍山公園枯等1個多小時後，向警方求助，找來5部計程車載往後龍高鐵站，再轉搭高鐵返回台北。當時氣憤的乘客曾向員警詢問，東西都還在遊覽車上，擔心物品遭竊，還要多花近新台幣500元車資，是否可提供報案紀錄，警方則回應，相關案情都有工作紀錄，可作為日後求償依據。

苗栗縣政府消保官王德基表示，針對這起事件，遊覽車司機「不管怎麼樣都不可以把遊客丟包」，如果消費者因此產生額外的交通費用及損失，可向消保官申訴、求償。
"""

In [59]:
stop_words = ['\n', '，', '。'] + list(string.digits)
''.join([w for w in news if w not in stop_words])

'苗栗警分局日傍晚接獲通報苗栗市貓貍山公園有民眾需要協助南苗派出所員警趕往現場發現名乘客手足無措因為原本載送他們的遊覽車已自行離去領隊臨時調不到其他車輛前往眼看天色漸暗不知如何是好警方調查這群來自台北的乘客相約出遊最後一站走訪苗栗市功維敘隧道疑似乘客希望領隊請遊覽車司機把車開下山接駁但司機認為山下無法停車要乘客走回山上坐車雙方僵持不下最後遊覽車司機竟掛電話直接把車開走遭丟包的乘客在貓貍山公園枯等個多小時後向警方求助找來部計程車載往後龍高鐵站再轉搭高鐵返回台北當時氣憤的乘客曾向員警詢問東西都還在遊覽車上擔心物品遭竊還要多花近新台幣元車資是否可提供報案紀錄警方則回應相關案情都有工作紀錄可作為日後求償依據苗栗縣政府消保官王德基表示針對這起事件遊覽車司機「不管怎麼樣都不可以把遊客丟包」如果消費者因此產生額外的交通費用及損失可向消保官申訴、求償'

## <font color=#0000FF>for與 list、if 混合使用(六)</font>

<font size = 3>請列出1-50之間3的倍數</font>

In [62]:
n = 50
[x for x in range(1, n + 1) if x%3 == 0]

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48]

<font size = 3>請列出 1-50 之間</font> 

- 偶數 : 加 1
- 奇數 : 乘 2

In [63]:
print([x+1 if x%2==0 else x*2 for x in range(1,51)])

[2, 3, 6, 5, 10, 7, 14, 9, 18, 11, 22, 13, 26, 15, 30, 17, 34, 19, 38, 21, 42, 23, 46, 25, 50, 27, 54, 29, 58, 31, 62, 33, 66, 35, 70, 37, 74, 39, 78, 41, 82, 43, 86, 45, 90, 47, 94, 49, 98, 51]


## <font color=#0000FF>nested (巢狀) for 使用(七)</font>

In [64]:
[(x, y) for x in range(1, 6) for y in range(11, 16)]    #()：tuple

[(1, 11),
 (1, 12),
 (1, 13),
 (1, 14),
 (1, 15),
 (2, 11),
 (2, 12),
 (2, 13),
 (2, 14),
 (2, 15),
 (3, 11),
 (3, 12),
 (3, 13),
 (3, 14),
 (3, 15),
 (4, 11),
 (4, 12),
 (4, 13),
 (4, 14),
 (4, 15),
 (5, 11),
 (5, 12),
 (5, 13),
 (5, 14),
 (5, 15)]

<font size=3>使用 zip() 合併多個物件</font>

In [65]:
X = range( 1,  6)
Y = range(11, 16)
Z = range(21, 26)
list(zip(X, Y, Z))

[(1, 11, 21), (2, 12, 22), (3, 13, 23), (4, 14, 24), (5, 15, 25)]

In [68]:
X = range( 1,  6)
Y = range(11, 16)
Z = range(21, 26)
[(x, y, z) for (x, y, z) in zip(X, Y, Z)]

[(1, 11, 21), (2, 12, 22), (3, 13, 23), (4, 14, 24), (5, 15, 25)]

<font size = 3 color=#0000FF>【練習題】撰寫一個 質數 的判斷程式</font>

<font size = 3> for ／ while迴圈可以使用： </font>

- break : 直接跳離開迴圈之外
- continue : 直接跳回至 for / while 之處

In [71]:
num = 23

isPrimeFlag = True     #先假設他是質數
for f in range(2, num):
    if num % f == 0:
        isPrimeFlag = False
        break
print(isPrimeFlag)

True


<font size=3> 改寫成函數</font>

In [74]:
def isPrime(num):
    #num = 23
    isPrimeFlag = True     #先假設他是質數
    for f in range(2, num):
        if num % f == 0:
            isPrimeFlag = False
            break
    return isPrimeFlag

In [79]:
isPrime(53)

True

<font size=3> 改用while迴圈</font>

In [82]:
num = 23
isPrimeFlag = True
f = 2
while isPrimeFlag and f < num:
    if num % f == 0:
        isPrimeFlag = False
    f = f + 1
print(isPrimeFlag)  

True


In [83]:
def isPrime2(num):
    isPrimeFlag = True
    f = 2
    while isPrimeFlag and f < num:
        if num % f == 0:
            isPrimeFlag = False
        f = f + 1
    return isPrimeFlag

In [85]:
isPrime2(25)

False

<font size=3>【練習】請輸入一個字串，其中包含文數字，過濾後，只輸出數字的部分</font>

In [102]:
mystr = "234ad5"
"".join([x for x in mystr if x in list(string.digits)])

'2345'